### ISSUE TITLE
Having troubles with github auth test on Github Actions CI

### ISSUE THREAD

**Issue by d-ivashchuk** [lirantal/cypress-social-logins#103]
Everything works fine till the point of actual authentication - github asks for verification of the device :D I guess that's pretty not solvable right now? maybe someone knows how to mitigate it.

**Comment by lirantal** [comment]
Hi there

Looks like you missed up on the disclaimer in the README: 
![image](https://user-images.githubusercontent.com/316371/124496630-58508d00-ddc2-11eb-9e2c-532ceba27194.png)

**Comment by d-ivashchuk** [comment]
Aha, missed indeed 🤔 don't know how could I have missed it, it being so prominent 🙈 

too bad, I thought I'd be able to cover both local testing and ci parts with this. Thanks for the heads up, and the plug-in is really awesome 👏🏼

Maybe you've personally stumbled on some example using mocked next-auth session with cypress? Otherwise thanks and we can close this!

**Comment by lirantal** [comment]
I haven't stumbled on anything else. It's a tricky thing to work around due to all the anti-fraud protections that these social networks employ for login.

One idea I can give you is that if you can work out the whole two-factor auth via API (to get the code) then you can definitely work around it and script it into this testing plugin.

**Comment by lirantal** [comment]
Goodluck and have fun!
