### ISSUE TITLE
Any update on Facebook login 

### ISSUE THREAD

**Issue by MehranShafqat** [lirantal/cypress-social-logins#27]
Is there any update on Facebook integration please ?

**Comment by lirantal** [comment]
Would you like to submit a PR for it? we'd be happy to support you :)

**Comment by cain** [comment]
@lirantal Id love to support Facebook integration, especially with the Facebook login/auth popup.

Im new to cypress and this plugin but would love to contribute this feature. Wondering if you could give me some guidance or help on where to start and what id need to do.

I see https://github.com/lirantal/cypress-social-logins/pull/22

**Comment by lirantal** [comment]
Happy to have you contributing this ❤️
I think definitely a good starting point is getting a bit familiar with Cypress itself. Create a sample project, configure this plan for it to do a login based on the currently supported Google integration and it will help you understand how things work and debug your way around it.

The idea is basically just like any other Cypress test - you navigate to a page, wait for specific inputs, put text in them, click a button. Actually, all of that is done in Puppeteer and not even in Cypress because Cypress doesn't support controlling other pages than that being tested (and the google connect, facebook etc are all outside the domain). The last part is the most important - you need to grab the cookies from the pupeteer authenticated session and set them in the Cypress context.

**Comment by cain** [comment]
@lirantal Thanks! I'll have a look around and may ask for some help or guidance if I get stuck :)

**Comment by lirantal** [comment]
@cain hope all goes well in these times.
if you need any help let me know!

**Comment by lirantal** [comment]
@cain if you wanted to catch up on it, I'd still be happy to merge other social login updates like Facebook.
Hope you're all safe and healthy ❤️

**Comment by patcon** [comment]
@lirantal might you be able to expand the google login with a bare minimal [nonfunctional] "dummy" provider? It's not clear where to hook in to extend from one to multiple...! I assume it's turning single values into objects somewhere, but clarity on that feels like it would open up others to chipping in more easily :) Thanks for considering

EDIT: my guess is just turning this

https://github.com/lirantal/cypress-social-logins/blob/65cb0e9a2fdfb1de218f64bd0ac598b8182e38fc/src/Plugins.js#L24

into

```js
module.exports = {
  GoogleSocialLogin = async function GoogleSocialLogin(options = {}) {
    // ...
  },
  FacbookSocialLogin = async function FacebookSocialLogin(options = {}) {
    // ...
  }
}
```

**Comment by lirantal** [comment]
@patcon indeed. Just create another function handler for the new provider and export it too.

**Comment by lirantal** [comment]
FYI @vikmaksimenko added support for login via GitHub and Microsoft: https://github.com/lirantal/cypress-social-logins/pull/53
