### ISSUE TITLE
Retrieve cookies from multiple domains

### ISSUE THREAD

**Issue by michellelievsay** [lirantal/cypress-social-logins#7]
Great plugin! This is a big factor in our choice to work with cypress.

Our app sets cookies in multiple domains as part of its auth process. Using this plugin we're able to get the required cookies for our own domain, but not the others we need.

We'd love to see an option to either get all cookies (for all domains) or to optionally provide a list of additional domains to get cookies from. 

Is there an existing way to accomplish this that I'm missing?

**Comment by lirantal** [comment]
Thanks for the kind words @michellelievsay ❤️

The method to retrieve the cookies after logging in is by calling puppeteer's `page.cookies` (https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagecookiesurls) using the login URL. Since this method supports a list of URLs to get cookies for we could optionally pass that for the list of URLs of all domains you need the cookies for and then set that for the test. Would that work for you?

**Comment by michellelievsay** [comment]
Yep that would work!

**Comment by lirantal** [comment]
Cool. Would you like to submit a PR or prefer me to prepare something on a branch that you can try this on?

**Comment by michellelievsay** [comment]
We'll submit a PR next week.

**Comment by lirantal** [comment]
Wonderful!
If you need any help with git or GitHub workflow to create the PR or any assistance with the code change involved ping me and I'd be happy to help you push this out.

**Comment by lirantal** [comment]
fixed by https://github.com/lirantal/cypress-social-logins/pull/8
