### ISSUE TITLE
can anybody offer a google login demo ?

### ISSUE THREAD

**Issue by ccc43542876** [lirantal/cypress-social-logins#80]

**Comment by kubenstein** [comment]
@lirantal Im seconding this. Looks like the project has all abilities we need but readme is just not clear or explicit enough.. Example would be really really appreciated. I stuck at configuring the setup and i think i cant go pass thru it, forcing me to just look somewhere else for functionality i feel is here. 
Where all those files should go,  why we need `loginUrl` when we want to login to google? This and many questions arise. 

I feel everything is ready just last step, so clear and explicit readme or example project is missing.

Cheers!

**Comment by lirantal** [comment]
@kubenstein I feel you, and wish I could help more but unfortunately, I don't have the time at the moment in putting a more elaborated example on the README.

There's a branch here https://github.com/lirantal/cypress-social-logins/tree/tests/add-cypress-e2e-second-go on the repo that should try to help on how to piece together the functionality. It doesn't work in CI due to the restrictions of captcha, etc., but perhaps would help you understand how to write the E2E tests. It's not a Google one, though.

> Where all those files should go, why we need loginUrl when we want to login to google? This and many questions arise.

See above for mostly about file structure and how to write the tets.
About `loginUrl`, is the README not clear enough on that? basically, this is where cypress/puppeteer under the hood, should navigate to, in order to click on a button that has the "Login with Google".

**Comment by lirantal** [comment]
New version of cypress-social-logins includes the latest Puppeteer.

Going to close this for being stale but if any issues remain or more context to be shared, please comment and will re-open.
